### ISSUE TITLE
keyboard hide textfield

### ISSUE THREAD

**Issue by pescabias** [fphilipe/PHFComposeBarView#50]
hi! thanks for this awesome work!

i was wandering about if you can help me with my issue, the textfield doesnt move above the keyboard when you tap on it. thankss

**Comment by fphilipe** [comment]
Hi. Check the example code in this repo. It does exactly what you're asking for. Alternatively use an input accessory view as shown [here](https://robots.thoughtbot.com/input-accessorizing-uiviewcontroller).

**Comment by dilizarov** [comment]
@fphilipe This is all very odd because in another project where I use this library, I don't have to do any set-up and this perfectly goes up and down with the keyboard. However, now, it isn't going up and down with the keyboard.

I followed the tutorial in your link above and it now goes up and down with the keyboard... but the textView is not selected. I can't even press it to select it. When I press a letter on the keyboard, my app crashes. Odd behavior.

**Comment by fphilipe** [comment]
@dilizarov Sorry, but I can't really help you. Maybe explain your problem on Stackoverflow. Good luck!
